package POJOS.POJO_B;
// Generated 09-abr-2016 13:40:41 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer id;
     private String cif;
     private String nombre;
     private String direccion;
     private String provincia;
     private String poblacion;
     private String cp;
     private int tlf;
     private int comercial;
     private Timestamp fechaAlta;
     private String contacto;
     private Set visitases = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(String cif, String nombre, String direccion, String provincia, String poblacion, String cp, int tlf, int comercial, Timestamp fechaAlta,String contacto) {
        this.cif = cif;
        this.nombre = nombre;
        this.direccion = direccion;
        this.provincia = provincia;
        this.poblacion = poblacion;
        this.cp = cp;
        this.tlf = tlf;
        this.comercial = comercial;
        this.fechaAlta = fechaAlta;
        this.contacto=contacto;
    }
    public Empresas(String cif, String nombre, String direccion, String provincia, String poblacion, String cp, int tlf, int comercial, Timestamp fechaAlta, String contacto, Set visitases) {
       this.cif = cif;
       this.nombre = nombre;
       this.direccion = direccion;
       this.provincia = provincia;
       this.poblacion = poblacion;
       this.cp = cp;
       this.tlf = tlf;
       this.comercial = comercial;
       this.fechaAlta = fechaAlta;
       this.contacto = contacto;
       this.visitases = visitases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public int getTlf() {
        return this.tlf;
    }
    
    public void setTlf(int tlf) {
        this.tlf = tlf;
    }
    public int getComercial() {
        return this.comercial;
    }
    
    public void setComercial(int comercial) {
        this.comercial = comercial;
    }
    public  Timestamp getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Timestamp fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getVisitases() {
        return this.visitases;
    }
    
    public void setVisitases(Set visitases) {
        this.visitases = visitases;
    }




}


