package POJOS.POJO_B;
// Generated 09-abr-2016 13:40:41 by Hibernate Tools 4.3.1



/**
 * Visitas generated by hbm2java
 */
public class Visitas  implements java.io.Serializable {


     private VisitasId id;
     private Empresas empresas;
     private Usuarios usuarios;
     private String fecha;
     private String resultado;
     private String motivo;

    public Visitas() {
    }

	
    public Visitas(VisitasId id, Empresas empresas, Usuarios usuarios) {
        this.id = id;
        this.empresas = empresas;
        this.usuarios = usuarios;
    }
    public Visitas(VisitasId id, Empresas empresas, Usuarios usuarios, String fecha, String resultado, String motivo) {
       this.id = id;
       this.empresas = empresas;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.resultado = resultado;
       this.motivo = motivo;
    }
   
    public VisitasId getId() {
        return this.id;
    }
    
    public void setId(VisitasId id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


