package POJOS.POJO_B;
// Generated 09-abr-2016 13:40:41 by Hibernate Tools 4.3.1



/**
 * VisitasId generated by hbm2java
 */
public class VisitasId  implements java.io.Serializable {


     private int usuariosId;
     private int empresasId;

    public VisitasId() {
    }

    public VisitasId(int usuariosId, int empresasId) {
       this.usuariosId = usuariosId;
       this.empresasId = empresasId;
    }
   
    public int getUsuariosId() {
        return this.usuariosId;
    }
    
    public void setUsuariosId(int usuariosId) {
        this.usuariosId = usuariosId;
    }
    public int getEmpresasId() {
        return this.empresasId;
    }
    
    public void setEmpresasId(int empresasId) {
        this.empresasId = empresasId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VisitasId) ) return false;
		 VisitasId castOther = ( VisitasId ) other; 
         
		 return (this.getUsuariosId()==castOther.getUsuariosId())
 && (this.getEmpresasId()==castOther.getEmpresasId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuariosId();
         result = 37 * result + this.getEmpresasId();
         return result;
   }   


}


